### ISSUE TITLE
Metricsmanager migration fails

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass-services#64]
This is the stacktrace:

```
Running migrations:
  Applying metricsmanager.0002_auto_20150930_1314...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 160, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/migrations/executor.py", line 63, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/migrations/executor.py", line 97, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/migrations/migration.py", line 107, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/migrations/operations/special.py", line 117, in database_forwards
    self.code(from_state.render(), schema_editor)
  File "/home/nico/src/policycompass/policycompass-services/apps/metricsmanager/migrations/0002_auto_20150930_1314.py", line 21, in set_random_acronym
    metric.save()
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/models/base.py", line 590, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/models/base.py", line 618, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/models/base.py", line 680, in _save_table
    forced_update)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/models/base.py", line 724, in _do_update
    return filtered._update(values) > 0
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/models/query.py", line 600, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1004, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 775, in execute_sql
    sql, params = self.as_sql()
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 969, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 627, in get_db_prep_save
    prepared=False)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 619, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/nico/src/policycompass/policycompass-services/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 1597, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'creator'
Makefile:92: recipe for target 'services_install' failed
make: *** [services_install] Error 1
```

**Comment by nidico** [comment]
Deleting the data helps:

    delete from metricsmanager_metric;

**Comment by nidico** [comment]
I think this has been resolved in the meantime and this is the wrong repo for bug reports anyway.
